### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by theseion**
Added test build for Python 3.10

Split from PR #66, part 2

### CODE REVIEW

**Review by fzipi — CHANGES_REQUESTED** [review]
Well, this one updates dependencies, but also tests.  Test should be only in the next PR.

**Comment by theseion** [comment]
I did that so the PR checks would run through and to show, that the change doesn't affect the tests. Do you still want me to change it?

**Comment by theseion** [comment]
@fzipi @fgsch this is the next one.

**Review by fzipi — APPROVED** [review]
LGTM now.

**Pull request merged**
