### PR TITLE
Python 3 support

### LINKED ISSUE #23: Python 3 support
Python 2 is on its way out. 

FTW should support Python 3 as well.

### PR DESCRIPTION
**Pull request by fgsch**
See individual commits for details.

Fixes #23.

### CODE REVIEW

**Comment by csanders-git** [comment]
wow, wow wow -- nice work -- check it @zmallen

**Comment by fgsch** [comment]
I broke things down the best I could so they can also be cherry picked, hence all the different commits.

Personally I'd prefer to work with bytes everywhere but that could be done at a later time.
I'd also like to apply some PEP8 love to be more consistent. Again, that can be done once this is merged.

**Comment by zmallen** [comment]
Wow! This is great and we really appreciate it. Itll take a few days for me to review, but ill be commenting as I go!

**Review by zmallen — CHANGES_REQUESTED** [review]
Can you bump the version to `1.2.0` in `setup.py`? Can you also add to `.travis.yml` a python3 container to test?

**Comment by fgsch** [comment]
I will bump the version. 
Not sure about the python3 container you are referring to. Can you elaborate?

**Comment by zmallen** [comment]
Sure thing! Inside `.travis.yml` it says to run the tests in a `python 2.7` environment. Can you append `python 3.6` and `python3.7` to that yaml clause to make sure its backwards/forwards compatible?

**Comment by fgsch** [comment]
3.7 is already there. I could add 3.6 but frankly I don't see the point.

**Comment by zmallen** [comment]
Oh wow, apologies. Its staring me right in the face there. Im going to approve this - thank you for all the work!

**Review by zmallen — APPROVED** [review]

**Pull request merged**
