### PR TITLE
Improved test support

### PR DESCRIPTION
**Pull request by theseion**
Support creation of log markers.

Split from PR #66, part 3

### CODE REVIEW

**Review by fzipi — APPROVED** [review]
LGTM.

If you don't mind, I probably squash the last two commits for a cleaner history.

**Comment by fzipi** [comment]
Oh, I can't do it using the GH interface. Can you squash those @theseion ?

**Comment by theseion** [comment]
Damn, you're fast 😄. Sure, squash ahead.

**Comment by theseion** [comment]
Apparently, I don't have write access to the repo, so no, I can't perform the merge / squash, sorry.

**Comment by fzipi** [comment]
No, I mean you last two commits. The last one fbca174 can be squashed with bdfb4b7.

**Pull request merged**
