### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by fgsch**
This fixes the plugin by correcting one import and ensuring the right dependencies are installed.

While I'm here I've made some minor cleanups and bumped the version.

### CODE REVIEW

**Comment by zmallen** [comment]
Can you squash and bump the version in `setup.py`?

**Comment by fgsch** [comment]
I can squash it (see below) but I don't want to bump it just yet as I have more things coming.

Personally, since these are separate changes, I'd prefer not to squash it as it explains why they were made but your call.

**Comment by zmallen** [comment]
I can take it or leave it - thoughts @csanders-git ?

**Comment by fgsch** [comment]
Ping

**Pull request merged**
