### PR TITLE
Pep8 and other fixes

### PR DESCRIPTION
**Pull request by fgsch**
This builds on top of #27 and should be reviewed afterwards.

It is mostly a combination of pycodestyle (pep8) changes and other cleanup from pyflakes.
In addition .travis.yml was changed to exercise the plugin and to ensure future changes follow pep8 and don't introduce errors.

This still doesn't bump the setup because I still want to do a few more things but they should be relatively small compared to this and #27.

### CODE REVIEW

**Comment by fgsch** [comment]
This is ready for review now.

**Comment by csanders-git** [comment]
on my todo for the day

**Comment by fgsch** [comment]
Ping

**Comment by csanders-git** [comment]
finally found some time to do this, nice work @fgsch

**Pull request merged**
